List HomeImages =[
  "Asset/Gallery Images/images/image1.jpg",
  "Asset/Gallery Images/images/image2.jpg",
  "Asset/Gallery Images/images/image3.jpg",
  "Asset/Gallery Images/images/image4.jpg",
  "Asset/Gallery Images/images/image5.jpg",
  "Asset/Gallery Images/images/image6.jpg",
  "Asset/Gallery Images/images/image7.jpg",
  "Asset/Gallery Images/images/image8.jpg",
  "Asset/Gallery Images/images/image9.jpg",
  "Asset/Gallery Images/images/image10.jpg",
  "Asset/Gallery Images/images/image11.jpg",
  "Asset/Gallery Images/images/image12.jpg",
];

List Imagename = [
  'Camera',
  'Family',
  'Facbbok',
  'Whatsapp',
  'Screenshot',
  'Instgram',
  'Collage',
  'Flowers',
  'animals',
  'Collage',
  'Flowers',
  'Animal',
];
List ImageQty = [
  '100',
  '200',
  '300',
  '400',
  '500',
  '600',
  '700',
  '800',
  '900',
  '100',
  '200',
  '300',
];
List HideImages =[
  "Asset/Gallery Images/images/hideimage1.jpg",
  "Asset/Gallery Images/images/hideimage7.jpg",
  "Asset/Gallery Images/images/hideimage5.jpg",
  "Asset/Gallery Images/images/hideimage4.jpg",
  "Asset/Gallery Images/images/hideimage8.jpg",
  "Asset/Gallery Images/images/hideimage6.jpg",
  "Asset/Gallery Images/images/hideimage3.jpg",
  "Asset/Gallery Images/images/hideimage2.jpg",
  "Asset/Gallery Images/images/hideimage9.jpg",
  "Asset/Gallery Images/images/hideimage10.jpg",
  "Asset/Gallery Images/images/hideimage11.jpg",
  "Asset/Gallery Images/images/hideimage12.jpg",
  "Asset/Gallery Images/images/hideimage13.jpg",
  "Asset/Gallery Images/images/image1.jpg",
  "Asset/Gallery Images/images/image2.jpg",
  "Asset/Gallery Images/images/image3.jpg",
  "Asset/Gallery Images/images/image4.jpg",
  "Asset/Gallery Images/images/image5.jpg",
  "Asset/Gallery Images/images/image6.jpg",
  "Asset/Gallery Images/images/image7.jpg",
  "Asset/Gallery Images/images/image8.jpg",
  "Asset/Gallery Images/images/image9.jpg",
  "Asset/Gallery Images/images/image10.jpg",
  "Asset/Gallery Images/images/image11.jpg",
  "Asset/Gallery Images/images/image12.jpg",
];